-- TRT-1989 Phase 4: Create Partitioned Tables
--
-- Creates two RANGE partitioned tables by timestamp (daily granularity):
--   - prow_job_run_tests (partitioned by prow_job_run_timestamp)
--   - prow_job_run_test_outputs (partitioned by prow_job_run_timestamp)
--
-- Partition creation (daily partitions) is handled separately via partition management system.

-- ============================================================================
-- prow_job_run_tests (RANGE partitioned)
-- ============================================================================

CREATE TABLE IF NOT EXISTS prow_job_run_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,

    prow_job_run_id BIGINT NOT NULL,
    prow_job_id BIGINT NOT NULL,
    prow_job_run_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    prow_job_run_release TEXT NOT NULL,
    test_id BIGINT NOT NULL,
    suite_id BIGINT,
    status INT,
    duration DOUBLE PRECISION,

    PRIMARY KEY (id, prow_job_run_timestamp)
) PARTITION BY RANGE (prow_job_run_timestamp);

-- Indexes for prow_job_run_tests
CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_timestamp
    ON prow_job_run_tests (prow_job_run_timestamp);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_prow_job_run_id
    ON prow_job_run_tests (prow_job_run_id);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_test_id
    ON prow_job_run_tests (test_id);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_status
    ON prow_job_run_tests (status);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_prow_job_id
    ON prow_job_run_tests (prow_job_id);

-- Composite index for Component Readiness queries
CREATE INDEX IF NOT EXISTS idx_prow_job_run_tests_test_id_status
    ON prow_job_run_tests (test_id, status);

-- Foreign key to prow_job_runs (note: cannot use CASCADE delete on partitioned table)
-- Referential integrity maintained by application layer
-- ALTER TABLE prow_job_run_tests
--     ADD CONSTRAINT IF NOT EXISTS fk_prow_job_run_tests_prow_job_run_id
--     FOREIGN KEY (prow_job_run_id)
--     REFERENCES prow_job_runs (id);
-- Skipped: FK constraints on partitioned tables create significant overhead

-- ============================================================================
-- prow_job_run_test_outputs (RANGE partitioned)
-- ============================================================================

CREATE TABLE IF NOT EXISTS prow_job_run_test_outputs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,

    prow_job_run_test_id BIGINT NOT NULL,
    output TEXT,
    prow_job_run_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    prow_job_run_test_release TEXT NOT NULL,

    PRIMARY KEY (id, prow_job_run_timestamp)
) PARTITION BY RANGE (prow_job_run_timestamp);

-- Indexes for prow_job_run_test_outputs
CREATE INDEX IF NOT EXISTS idx_prow_job_run_test_outputs_timestamp
    ON prow_job_run_test_outputs (prow_job_run_timestamp);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_test_outputs_prow_job_run_test_id
    ON prow_job_run_test_outputs (prow_job_run_test_id);

CREATE INDEX IF NOT EXISTS idx_prow_job_run_test_outputs_release_timestamp
    ON prow_job_run_test_outputs (prow_job_run_test_release, prow_job_run_timestamp);

-- Foreign key to prow_job_run_tests (both tables partitioned)
-- Referential integrity maintained by application layer
-- ALTER TABLE prow_job_run_test_outputs
--     ADD CONSTRAINT IF NOT EXISTS fk_prow_job_run_test_outputs_prow_job_run_test_id
--     FOREIGN KEY (prow_job_run_test_id, prow_job_run_timestamp)
--     REFERENCES prow_job_run_tests (id, prow_job_run_timestamp);
-- Skipped: FK constraints on partitioned tables create significant overhead
